#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

path=($HOME/.bin $HOME/.local/bin $HOME/Applications $HOME/.config/adb-fastboot/platform-tools $path)
typeset -U path PATH
export PATH

export ALTERNATE_EDITOR=""                        # setting for emacsclient
export EDITOR="emacsclient -t -a ''"              # $EDITOR use Emacs in terminal
export VISUAL="emacsclient -c -a emacs"           # $VISUAL use Emacs in GUI mode
export BROWSER="firefox"
export TERM="xterm-256color"
