#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bash,bin,fzf,nvim,rofi,sway,terms,tmux,zsh,private"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g"); do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
