#! /bin/sh

chosen=$(printf "  Power Off\n  Suspend\n  Restart" | rofi -dmenu -i -theme-str '@import "power.rasi"')

case "$chosen" in
	"  Power Off") poweroff ;;
	"  Suspend") systemctl suspend ;;
	"  Restart") reboot ;;
	*) exit 1 ;;
esac